# Generated by Django 3.0.1 on 2019-12-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_cust.jpg', upload_to='cust_pics')),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryguy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default_dlvr.jpg', upload_to='delvrygy_pics')),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
                ('drvlicence', models.ImageField(default='licence.jpg', upload_to='delvrygy_pics/docs')),
                ('docname', models.CharField(max_length=50)),
                ('verfdoc', models.ImageField(default='doc.jpg', upload_to='dlvrygy_pics/docs')),
            ],
        ),
    ]
