# Generated by Django 3.0.1 on 2019-12-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=40)),
                ('cprice', models.FloatField()),
                ('sprice', models.FloatField()),
                ('mrp', models.FloatField()),
                ('tax', models.FloatField(default=0.0)),
                ('stock', models.PositiveIntegerField()),
                ('units', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
