# Generated by Django 3.0.1 on 2019-12-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='item_pics'),
        ),
    ]
