# Generated by Django 3.0.1 on 2019-12-28 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20191224_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custId', models.IntegerField(max_length=10)),
                ('contact', models.IntegerField(max_length=10)),
                ('amount', models.FloatField(max_length=10)),
                ('productsId', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('Address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
