# Generated by Django 3.0.1 on 2019-12-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dagent',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='In Process', max_length=10),
            preserve_default=False,
        ),
    ]
