# Generated by Django 3.0.1 on 2019-12-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20191228_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='dagent',
            field=models.IntegerField(max_length=10),
        ),
    ]
