# Generated by Django 3.0.1 on 2019-12-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20191228_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='custId',
            field=models.CharField(max_length=10),
        ),
    ]
